name: lint-test-typecheck

on:
    push:
        branches:
            - "**"
            - "!release"

jobs:
    build:
        name: "Build, lint, typecheck and test"
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v1
            - name: Lint and test
              if: "!contains(github.event.head_commit.message, '[ci skip release]') && !contains(github.ref, 'greenkeeper')"
              run: |
                  yarn install --frozen-lockfile
                  yarn build
                  yarn ci:test
            - name: Lint and test (greenkeeper)
              if: contains(github.ref, 'greenkeeper')
              run: |
                  yarn install
                  yarn build
                  yarn ci:test
