name: lint-test-typecheck

on:
    push:
        branches:
            - "**"
            - "!release"
        paths:
            - "jest/*"
            - "packages/*.ts"
            - "packages/*.tsx"
            - "patches/*"
            - "portal/*.ts"
            - "portal/*.tsx"
            - "yarn.lock"

jobs:
    build:
        name: "Build, lint, typecheck and test"
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2.3.4

            - name: Get yarn cache directory path
              id: yarn-cache-dir-path
              run: echo "::set-output name=dir::$(yarn cache dir)"

            - name: Cache yarn directory
              uses: actions/cache@v2.1.6
              id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
              with:
                  path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
                  key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-yarn-

            - name: Lint and test
              if: "!contains(github.event.head_commit.message, '[ci skip release]')"
              run: |
                  yarn install --frozen-lockfile
                  yarn build
                  yarn ci:test
